### ISSUE TITLE
Login button has changed. Please contact support. 

### ISSUE THREAD

**Issue by BlaydeRunner08** [simao-silva/noip-renewer#30] opened 2023-04-25 19:21 UTC
Running from a Synology NAS, receive the following:

`Opening browser`
`Login button has changed. Please contact support. `

I've tried multiple times on multiple days, with no luck.

This is the same issue as #27 , but that one was closed by accident it seems.

I have a full linux vm that is running https://github.com/loblab/noip-renew, that seems to still be working properly.

**Comment by simao-silva** [comment] 2023-04-28 00:45
Hi,

I have tested both latest debian and alpine variants and both ran successfully. 
That error can also occur if, for example, NOIP requires you to complete a captcha or you have NOIP set to another language that is not English. Is any of this your case? Have you tried access your NOIP account page and log in only using your username and password?

**Comment by BlaydeRunner08** [comment] 2023-04-28 15:52
I quickly popped it onto a test Ubuntu VM, and it worked perfectly, but for some reason, i can't get it to run properly on my Synology... what am I missing here?

**Comment by BlaydeRunner08** [comment] 2023-04-28 16:31
I ssh'd into the NAS and ran the exact same command that ran perfectly on my ubuntu VM, and it gave me the same error as before...

**Comment by simao-silva** [comment] 2023-05-10 00:43
Unfortunately, I don't know what it could be and I am unable to reproduce this.  I will close this until further new developments.

**Closed by simao-silva** 2023-05-10 00:43 UTC

**Comment by cfr2305** [comment] 2023-08-27 11:26
Hi, just because I was facing the same issue on my Synology... In my case the problem was the Pi-hole.
