### ISSUE TITLE
bad news : they add a recaptcha page after the "no thanks confirm page".

### ISSUE THREAD

**Issue by homefefeld** [simao-silva/noip-renewer#18] opened 2022-11-07 10:47 UTC
bad news : they add a recaptcha page after the "no thanks confirm page".

**Comment by djrm05** [comment] 2022-11-12 11:23
yep, it seems that stop working at all...

Opening browser
Traceback (most recent call last):
  File "//renew.py", line 75, in <module>
    i.click()
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=102.0.5005.182)

**Comment by simao-silva** [comment] 2022-11-12 12:00
Is this a one time thing or it happens regularly or even every time?

**Comment by djrm05** [comment] 2022-11-12 12:01
I think this happens once every time that you are confirming the host.

**Comment by RomyxBaps** [comment] 2022-11-14 08:50
Hi,
I jave the same error since mutliple days :
```
docker run --rm -i simaofsilva/noip-renewer staff@digdeo.fr SP859kfV28sTByy6
Opening browser
Traceback (most recent call last):
  File "//renew.py", line 75, in <module>
    i.click()
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=102.0.5005.182)

```

**Comment by RomyxBaps** [comment] 2022-11-16 15:24
Thank you for your response.
I have an other error with the tag e9cd110-debian : 
```
Opening browser
Traceback (most recent call last):
  File "//renew.py", line 75, in <module>
    i.click()
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=106.0.5249.61)
Stacktrace:
#0 0x7ff459b08d43 <unknown>
#1 0x7ff4598f5501 <unknown>
#2 0x7ff4598e2776 <unknown>
#3 0x7ff4598e1e86 <unknown>
#4 0x7ff4598e118f <unknown>
#5 0x7ff4598e1039 <unknown>
#6 0x7ff4598e001a <unknown>
#7 0x7ff4598e0659 <unknown>
#8 0x7ff4598f212f <unknown>
#9 0x7ff4598f29d2 <unknown>
#10 0x7ff4598fddbf <unknown>
#11 0x7ff459901d9a <unknown>
#12 0x7ff4598e0a94 <unknown>
#13 0x7ff4598fda38 <unknown>
#14 0x7ff459969959 <unknown>
#15 0x7ff459953823 <unknown>
#16 0x7ff4599222d6 <unknown>
#17 0x7ff4599238a8 <unknown>
#18 0x7ff459b46f9d <unknown>
#19 0x7ff459b48be0 <unknown>
#20 0x7ff459b486e7 <unknown>
#21 0x7ff459b49275 <unknown>
#22 0x7ff459b3620b <unknown>
#23 0x7ff459b495a6 <unknown>
#24 0x7ff459b2a65f <unknown>
#25 0x7ff459b61fd5 <unknown>
#26 0x7ff459b62173 <unknown>
#27 0x7ff459b7b7d0 <unknown>
#28 0x7ff4594fdea7 <unknown>
```

**Comment by RomyxBaps** [comment] 2022-11-17 10:33
Working with the latest update yesterday.

**Comment by dkrjvi** [comment] 2022-11-18 09:46
Hi,
Downloaded latest now - still does not work.

![image](https://user-images.githubusercontent.com/46902834/202671847-fa9e71ab-41ac-4f14-81e7-9e47b974cda0.png)

**Comment by simao-silva** [comment] 2022-11-21 02:16
From what I have seen, the error is a know bug (https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121). Although the error seems to be fixed in Chromium v104, I was still unable to run the script successfully even in Chromium v107. So, from the time being, the script will run with Firefox. Please check if the latest versions (e.g. tags with prefix `a52e871`) are working for you.

**Comment by lilws** [comment] 2022-11-22 09:13
I got this error when using tag #a52e871-debian or #latest

> Opening browser
> Login successful
> Confirming hosts phase
> Error:  Message: The element reference of <tr class="table-striped-row"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
> Stacktrace:
> WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
> StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.jsm:467:5
> element.resolveElement@chrome://remote/content/marionette/element.js:681:11
> evaluate.fromJSON@chrome://remote/content/marionette/evaluate.js:254:26
> evaluate.fromJSON@chrome://remote/content/marionette/evaluate.js:262:29
> evaluate.fromJSON@chrome://remote/content/marionette/evaluate.js:262:29
> receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:79:29
> 
> Logging off

**Comment by simao-silva** [comment] 2022-11-22 12:42
I run it in my laptop and Raspberry Pi and I did not get your error:

```
ubuntu@ubuntu:~$ docker run -i -t --rm simaofsilva/noip-renewer:a52e871-debian
Email: *******
Password: 
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
```

Have you tried running it a second time?

**Comment by lilws** [comment] 2022-11-22 13:00
I did run it for several times and still got the same error. Btw, when I go to Hostname page. It has the sentence state that "redemption in 5 days". I'm not sure if it relevant. I don't remember there is sentence like that.

**Comment by djrm05** [comment] 2022-11-23 08:31
> I run it in my laptop and Raspberry Pi and I did not get your error:
> 
> ```
> ubuntu@ubuntu:~$ docker run -i -t --rm simaofsilva/noip-renewer:a52e871-debian
> Email: *******
> Password: 
> Opening browser
> Login successful
> Confirming hosts phase
> 0 hosts confirmed
> Finished
> Logging off
> ```
> 
> Have you tried running it a second time?

Latest works for me as well without issues

**Comment by lilws** [comment] 2022-11-23 12:28
> > Have you tried running it a second time?
> 
> Latest works for me as well without issues

Well, I must confirm manually since that error occurs. So I did test again and when there is no host to confirm, it just running fine. I will check back later if the error still there next months.

**Comment by suhiymof** [comment] 2022-11-24 02:08
> I got this error when using tag #a52e871-debian or #latest
> 
> > Opening browser
> > Login successful
> > Confirming hosts phase
> > Error:  Message: The element reference of  is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
> > Stacktrace:
> > WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
> > StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.jsm:467:5
> > element.resolveElement@chrome://remote/content/marionette/element.js:681:11
> > evaluate.fromJSON@chrome://remote/content/marionette/evaluate.js:254:26
> > evaluate.fromJSON@chrome://remote/content/marionette/evaluate.js:262:29
> > evaluate.fromJSON@chrome://remote/content/marionette/evaluate.js:262:29
> > receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:79:29
> > Logging off

I got the same error. Did you solved it?

**Comment by simao-silva** [comment] 2022-11-24 03:23
Yes, I believe I did. I tested that image and I did not have any errors. Other users have also reported that the new images are working.

**Comment by zx900930** [comment] 2022-12-07 07:46
```
Untagged: simaofsilva/noip-renewer:latest
Untagged: simaofsilva/noip-renewer@sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f
Deleted: sha256:4353d70cb7bec1e2af273045e3c3a3a961ebec0a26bb85d46d87baa892430883
Deleted: sha256:aad9008ce0299a8224517699a30d7d62244e9caf90657ec90be419c56cdf7879
Deleted: sha256:26598874ac1f23cb3e6103b344f917ea5f67e7108653bf5037a34d47e6b10192
Deleted: sha256:0927ef3e8a7fb825cf20a06c7f19e3af985b29650b3d5b46b8e4b75dcfd4fb4f
Deleted: sha256:bcd052c374a78dc615c6f66f4dd59b123b6eff73befdc7c1989ec1d4a7ec8eea
Deleted: sha256:61327df74ea566fb3cbcfb1f4fefea248dcb565d2dbfe2efcfc85c0696eea696
Deleted: sha256:d68ef5a4818c85b31c206b8e670d87aad8faf75c74b65709a0e7b7679c1ca69e
Deleted: sha256:462a3c6fb4bb5af41e72c24b36e2bda62fc3a2f2a045e10e9c2542ded9f67b4e
Unable to find image 'simaofsilva/noip-renewer:latest' locally
latest: Pulling from simaofsilva/noip-renewer
c158987b0551: Already exists
7ec3a91b66d9: Pulling fs layer
2a66ef9569bf: Pulling fs layer
51ba2aaea185: Pulling fs layer
4fe55734f00f: Pulling fs layer
1d5f14127dc2: Pulling fs layer
172853a05d07: Pulling fs layer
994867cc3738: Pulling fs layer
1d5f14127dc2: Waiting
172853a05d07: Waiting
4fe55734f00f: Waiting
994867cc3738: Waiting
51ba2aaea185: Verifying Checksum
51ba2aaea185: Download complete
7ec3a91b66d9: Verifying Checksum
7ec3a91b66d9: Download complete
2a66ef9569bf: Verifying Checksum
2a66ef9569bf: Download complete
7ec3a91b66d9: Pull complete
4fe55734f00f: Verifying Checksum
4fe55734f00f: Download complete
2a66ef9569bf: Pull complete
51ba2aaea185: Pull complete
4fe55734f00f: Pull complete
994867cc3738: Verifying Checksum
994867cc3738: Download complete
172853a05d07: Verifying Checksum
172853a05d07: Download complete
1d5f14127dc2: Verifying Checksum
1d5f14127dc2: Download complete
1d5f14127dc2: Pull complete
172853a05d07: Pull complete
994867cc3738: Pull complete
Digest: sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f
Status: Downloaded newer image for simaofsilva/noip-renewer:latest
Opening browser
Login button has changed. Please contact support.
Opening browser
Login button has changed. Please contact support.
```
My cronjob stopped working about a week, it shows Login button has changed

**Comment by simao-silva** [comment] 2022-12-08 15:27
I've run the image with that specific digest without any errors. Please try to login on NOIP with a browser to see if no extra buttons / confirm pages appear related to your account.

**Comment by zx900930** [comment] 2022-12-08 20:05
> I've run the image with that specific digest without any errors. Please try to login on NOIP with a browser to see if no extra buttons / confirm pages appear related to your account.

Its just that `alpine@sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f` image is not working, After switching to simaofsilva/noip-renewer:debian it starts working now.
```
Digest: sha256:d3e22ec6a2b27ec7e9345757ea96ab4dcd6dfd3bf6a782bf71ba28a9e02bb893
Digest: sha256:d3e22ec6a2b27ec7e9345757ea96ab4dcd6dfd3bf6a782bf71ba28a9e02bb893
Status: Downloaded newer image for simaofsilva/noip-renewer:debian
Status: Downloaded newer image for simaofsilva/noip-renewer:debian
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
```
 switching back to digist `sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f`
or even the latest `sha256:395d0426e9b0fcf2869cbab762c149632ad74241d6f1cef7853d8d3e9d1c13f4` are not working

```
Unable to find image 'simaofsilva/noip-renewer@sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f' locally
docker.io/simaofsilva/noip-renewer@sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f: Pulling from simaofsilva/noip-renewer
c158987b0551: Already exists
7ec3a91b66d9: Pull complete
2a66ef9569bf: Pull complete
51ba2aaea185: Pull complete
4fe55734f00f: Pull complete
1d5f14127dc2: Pull complete
172853a05d07: Pull complete
994867cc3738: Pull complete
Digest: sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f
Status: Downloaded newer image for simaofsilva/noip-renewer@sha256:0457f19f55f6e46f29fc32f4bc251c8d0551a67f000804c266c460c168cbbb4f
Opening browser
Login button has changed. Please contact support.
```
the noip page seems normal without extra popups or buttons
![image](https://user-images.githubusercontent.com/734749/206554082-066c49d1-d25d-493e-bfee-d3017a1743dc.png)
![image](https://user-images.githubusercontent.com/734749/206552640-288695d0-a195-4820-b42d-7ecef4e9cf04.png)

**Comment by simao-silva** [comment] 2022-12-11 16:37
@zx900930 I've tested all the images you shared and I did not get any errors. Maybe it was a temporary issue with NO-IP?

**Comment by zx900930** [comment] 2022-12-11 16:59
> @zx900930 I've tested all the images you shared and I did not get any errors. Maybe it was a temporary issue with NO-IP?

yes, your images are good, it just because my ISP temporary blocking part of noip's frontend elements causing the login button not displayed correctely.

**Comment by mofakhar** [comment] 2023-01-04 04:09
I confirm that the issue is still present since they have added a confirmation step as you're not a Robot.
Below, the error message that we see and confirm the missing validation:

`Opening browser
Login successful
Confirming hosts phase
Error:  Message: The element reference of <tr class="table-striped-row"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:463:5
element.resolveElement@chrome://remote/content/marionette/element.sys.mjs:679:11
evaluate.fromJSON@chrome://remote/content/marionette/evaluate.sys.mjs:257:31
evaluate.fromJSON@chrome://remote/content/marionette/evaluate.sys.mjs:265:29
evaluate.fromJSON@chrome://remote/content/marionette/evaluate.sys.mjs:265:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:74:34

Logging off
`

**Comment by simao-silva** [comment] 2023-01-06 09:19
@mofakhar I am not able to reproduce that error. If that happens in a recurrent way on your side, please open a PR so it can be added to the code.

**Closed** 2023-01-06 11:10 UTC
