### ISSUE TITLE
Login button has changed. Please contact support.

### ISSUE THREAD

**Issue by daNutzzzzz** [simao-silva/noip-renewer#10] opened 2022-04-02 09:52 UTC
Hi,

Just installed this and after what seems to be a successful login, im then presented with the following "Login button has changed. Please contact support." error:

```
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
```

Using: **simaofsilva/noip-renewer:latest**

**Comment by simao-silva** [comment] 2022-04-05 16:42
That is odd since it has done the first attempt successfully and failed the second one. Have you tried rerun it on a different time?

**Comment by daNutzzzzz** [comment] 2022-04-06 11:41
Ive left it running, here is the latest logs:

`Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
Opening browser
Login button has changed. Please contact support. 
`

**Comment by simao-silva** [comment] 2022-04-07 23:31
How are you running it? 
Which environment are you using?

**Comment by daNutzzzzz** [comment] 2022-04-08 11:11
`    noip_renew:
        container_name: noip_renew
        environment:
            - 'PUID=1000'
            - 'PGID=100'
            - 'TZ=Europe/London'
        network_mode: bridge
        restart: unless-stopped
        command: <USERNAME> <PASSWORD>
        image: simaofsilva/noip-renewer:latest
`

`Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.10
  Git commit:       9070fa8
  Built:            Fri Mar 11 10:53:00 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

**Comment by simao-silva** [comment] 2022-04-08 14:40
Based on your answer, I am assuming you are using docker-compose. That said, I was not able to reproduce it since the YAML parser found errors. Still, I present you a working configuration: 
```
version: "3.6"

services:
  noip_renew:
    container_name: noip_renew
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/London'
    network_mode: bridge
    restart: unless-stopped
    command: [ "<EMAIL>" , "<PASSWORD>" ]
    image: simaofsilva/noip-renewer:latest
```

**Comment by daNutzzzzz** [comment] 2022-04-08 15:19
Is there a way to schedule the task to run say once an hour and not every minute?

**Comment by simao-silva** [comment] 2022-04-10 21:27
There is no scheduling regarding the script. It should start and end without any issues. I don't know why it is behaving on your environment that way. The script has a `exit 1` after the error message to avoid precisely cases like this. 
Does your environment have memory (RAM) constraints? Have you tried running on a different device?

**Comment by daNutzzzzz** [comment] 2022-04-13 19:57
Hi, ive just tried on another server and im seeing the same results in the logs

**Comment by daNutzzzzz** [comment] 2022-05-15 18:13
still an issue

**Comment by daNutzzzzz** [comment] 2022-05-17 11:16
Im also noticing that the container is constantly rebooting, is that by design?

**Comment by simao-silva** [comment] 2022-05-17 11:23
> Im also noticing that the container is constantly rebooting, is that by design?

No, it is not. That combine with the issues you reported before leads to believe that is a problem with your environment.

**Comment by daNutzzzzz** [comment] 2022-05-17 15:28
> still an issue
`Login button has changed. Please contact support.` is resolved as pihole is the same culprit as: https://github.com/simao-silva/noip-renewer/issues/8#issuecomment-1054498048

**Comment by daNutzzzzz** [comment] 2022-05-17 15:30
> > Im also noticing that the container is constantly rebooting, is that by design?
> 
> No, it is not. That combine with the issues you reported before leads to believe that is a problem with your environment.

ive just run this in a linode fresh vps and another ubuntu server offsite.. all reboot after `Logging off` stage "completes"

**Comment by simao-silva** [comment] 2022-06-04 11:45
So the error still remains or it is resolved?

**Comment by daNutzzzzz** [comment] 2022-06-05 21:07
> So the error still remains or it is resolved?

The shutdown/reboot issue is not.

**Comment by simao-silva** [comment] 2022-06-06 23:02
Try running the debug image. Make sure to create a local directory named `photos`. 
```
docker run -i -t --rm -v "$(realpath photos)":/photos simaofsilva/noip-renewer:debug
```
On a regular run, it creates 4 browser prints. Image 2 must be a print of the login form filled with your credentials; image 3 prints the NoIP dashboard and image 4 must print the page with the domains. Can you try it and check where the errors are  happening?

**Comment by daNutzzzzz** [comment] 2022-06-20 12:33
Apolgies for the late response.

Ive made this change and the  shuitdown/reboot issue still happens, however ive caught a couple of issues in the liogs;

```Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


Traceback (most recent call last):
  File "//renew.py", line 138, in <module>
    browser.get(LOGOUT_URL)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 442, in get
    self.execute(Command.GET, {'url': url})
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.236
  (Session info: headless chrome=102.0.5005.61)
Stacktrace:
#0 0x55876320f913 <unknown>
#1 0x558762f24fa6 <unknown>
#2 0x558762f0e4c5 <unknown>
#3 0x558762f0d2b2 <unknown>
#4 0x558762f0d8d9 <unknown>
#5 0x558762f21da8 <unknown>
#6 0x558762f22642 <unknown>
#7 0x558762f2ccaf <unknown>
#8 0x558762f303aa <unknown>
#9 0x558762f0dc36 <unknown>
#10 0x558762f2caf7 <unknown>
#11 0x558762f93b05 <unknown>
#12 0x558762f80f63 <unknown>
#13 0x558762f50b9b <unknown>
#14 0x558762f523ce <unknown>
#15 0x55876324be1d <unknown>
#16 0x55876324e753 <unknown>
#17 0x55876324e449 <unknown>
#18 0x55876324ed62 <unknown>
#19 0x55876323c1ab <unknown>
#20 0x55876324efe1 <unknown>
#21 0x558763231867 <unknown>
#22 0x558763265925 <unknown>
#23 0x558763265ac3 <unknown>
#24 0x5587632801e1 <unknown>
#25 0x7f92d9fe8ea7 <unknown>
```

or

```No log line matching the '' filter```

or

```Opening browser
Error: cannot login. Check if account is not blocked.
Logging off
```


With the error above account blocked, i can confirm its not, and here is the image capture.. i marked out the username.. only images 1&2 are present in the photos folder. However please, note, on previous attempts its logged in fine before "crashing".


![2](https://user-images.githubusercontent.com/89404081/174602353-347da06e-159a-4db4-8713-05628c97fea6.png)

**Comment by simao-silva** [comment] 2022-06-24 23:23
I don't know what seems to see the problem but it is related to your environment. I will close this issue since the problem is external to the context of this repository.

**Closed by simao-silva** 2022-06-24 23:23 UTC
